<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>ISYE 6414 Class Notes</title>
  <meta name="description" content="Notes from Spring 2021 semester of ISYE 6414 - Regression Analysis." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="ISYE 6414 Class Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Notes from Spring 2021 semester of ISYE 6414 - Regression Analysis." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="ISYE 6414 Class Notes" />
  
  <meta name="twitter:description" content="Notes from Spring 2021 semester of ISYE 6414 - Regression Analysis." />
  

<meta name="author" content="John Walker" />


<meta name="date" content="2021-01-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ISYE 6414 - Regression Analysis Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="Module-1.html"><a href="#module-1"><i class="fa fa-check"></i><b>1</b> Module 1</a>
<ul>
<li class="chapter" data-level="1.1" data-path="Module-1.html"><a href="#topic-1.1"><i class="fa fa-check"></i><b>1.1</b> Topic 1.1</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="Module-1.html"><a href="#lesson-1---regression-concepts-basics"><i class="fa fa-check"></i><b>1.1.1</b> Lesson 1 - Regression Concepts: Basics</a></li>
<li class="chapter" data-level="1.1.2" data-path="Module-1.html"><a href="#lesson-2---regression-concepts-estimation"><i class="fa fa-check"></i><b>1.1.2</b> Lesson 2 - Regression Concepts: Estimation</a></li>
<li class="chapter" data-level="1.1.3" data-path="Module-1.html"><a href="#lesson-3---regression-concepts-estimation-example"><i class="fa fa-check"></i><b>1.1.3</b> Lesson 3 - Regression Concepts: Estimation Example</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="Module-1.html"><a href="#topic-1.2"><i class="fa fa-check"></i><b>1.2</b> Topic 1.2</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="Module-1.html"><a href="#lesson-4---statistical-inference"><i class="fa fa-check"></i><b>1.2.1</b> Lesson 4 - Statistical Inference</a></li>
<li class="chapter" data-level="1.2.2" data-path="Module-1.html"><a href="#lesson-5---statistical-inference-examples"><i class="fa fa-check"></i><b>1.2.2</b> Lesson 5 - Statistical Inference Examples</a></li>
<li class="chapter" data-level="1.2.3" data-path="Module-1.html"><a href="#lesson-6---regression-line-and-prediction"><i class="fa fa-check"></i><b>1.2.3</b> Lesson 6 - Regression Line and Prediction</a></li>
<li class="chapter" data-level="1.2.4" data-path="Module-1.html"><a href="#lesson-7---regression-line-and-prediction-examples"><i class="fa fa-check"></i><b>1.2.4</b> Lesson 7 - Regression Line and Prediction Examples</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="Module-1.html"><a href="#topic-1.3"><i class="fa fa-check"></i><b>1.3</b> Topic 1.3</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="Module-1.html"><a href="#lesson-8---assumptions-and-diagnostics"><i class="fa fa-check"></i><b>1.3.1</b> Lesson 8 - Assumptions and Diagnostics</a></li>
<li class="chapter" data-level="1.3.2" data-path="Module-1.html"><a href="#lesson-9---outliers-and-model-performance"><i class="fa fa-check"></i><b>1.3.2</b> Lesson 9 - Outliers and Model Performance</a></li>
<li class="chapter" data-level="1.3.3" data-path="Module-1.html"><a href="#lesson-10---model-diagnostic-example"><i class="fa fa-check"></i><b>1.3.3</b> Lesson 10 - Model Diagnostic Example</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="Module-1.html"><a href="#topic-1.4"><i class="fa fa-check"></i><b>1.4</b> Topic 1.4</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="Module-1.html"><a href="#lesson-11---testing-the-theory-of-purchasing-power-parity-part-1"><i class="fa fa-check"></i><b>1.4.1</b> Lesson 11 - Testing the Theory of Purchasing Power Parity (Part 1)</a></li>
<li class="chapter" data-level="1.4.2" data-path="Module-1.html"><a href="#lesson-12---testing-the-theory-of-purchasing-power-parity-part-2"><i class="fa fa-check"></i><b>1.4.2</b> Lesson 12 - Testing the Theory of Purchasing Power Parity (Part 2)</a></li>
<li class="chapter" data-level="1.4.3" data-path="Module-1.html"><a href="#lesson-13---2000-presidential-election-in-florida"><i class="fa fa-check"></i><b>1.4.3</b> Lesson 13 - 2000 Presidential Election in Florida</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ISYE 6414 Class Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">ISYE 6414 Class Notes</h1>
<p class="author"><em>John Walker</em></p>
<p class="date"><em>2021-01-21</em></p>
</div>
<div id="module-1" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Module 1</h1>
<div id="topic-1.1" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Topic 1.1</h2>
<div id="lesson-1---regression-concepts-basics" class="section level3" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Lesson 1 - Regression Concepts: Basics</h3>
<p><strong>Regression analysis</strong> is one of the simplest ways to evaluate the relationship between two or more variables. Two main topics in this course: standard linear regression and <strong>generalized linear models</strong>.</p>
<p>Module 1 will cover a few examples:</p>
<ul>
<li><p>First example: a company that sells medical supplies to hospitals - is there a relationship between sales and advertising? Data includes yearly sales and advertising expenditure.</p></li>
<li><p>Second example: test the principle of PPP (purchasing power parity). This is theory that over long periods of time the exchange rate changes will tend to offset the differences in inflation rate between two countries. Data is inflation difference and exhange rate change for several countries.</p></li>
<li><p>Third example: From the 2000 election, try to predict whether votes cast in Palm Beach County for Buchanan were actually meant for Bush. This dataset contains many many variables.</p></li>
</ul>
<p>In regression, the variable we are interested in understanding is reffered to as the <strong>response (dependent) variable</strong>. The variables that we think might be useful in modelling the response variable are the <strong>predicting (explanatory/independent) variables</strong>.</p>
<p>The response variable is a <strong>random</strong> variable - because it varies with changes in the predictor along with other random changes.</p>
<p>The predicting variable is a <strong>fixed</strong> variable, it does not change with the response, but is set before the response is measured.</p>
<p><strong>Simple Linear Regression</strong>
<em>Fits a line to two dimensional data.</em></p>
<p><span class="math display">\[Y = \beta_{0} + \beta_{1} + \epsilon\]</span></p>
<p><strong>Mutiple Linear Regression</strong>
<em>Fits a plane to multiple dimensions.</em></p>
<p><span class="math display">\[Y = \beta_{0} + \beta_{1}X_1 + \beta_{2}X_2 + \epsilon\]</span></p>
<p><strong>Polynomial Linear Regression</strong>
<em>Fits a curved line to data points.</em></p>
<p><span class="math display">\[Y = \beta_{0} + \beta_{1}X + \beta_{2}X^2 + \epsilon\]</span></p>
<p>Regression is used for:</p>
<ul>
<li>Prediction of response</li>
<li>Modelling the relationship b/t response and predictors</li>
<li>Testing hypothesis of associations</li>
</ul>
<p>Virtually all other methods for studying dependence among variables are variations on the idea of linear regression.</p>
</div>
<div id="lesson-2---regression-concepts-estimation" class="section level3" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Lesson 2 - Regression Concepts: Estimation</h3>
<p>This lesson will cover the modelling framework for simple linear regression and the estimation approach.</p>
<p>The goal is to find the best line that describes a simple linear relationship, estimating <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span>.</p>
<p>Data is <em>n</em> pairs of <em>X</em> and <em>Y</em> data points.</p>
<p>Assumptions:</p>
<ul>
<li>Linearity/Mean Zero Assumption: <span class="math inline">\(E_i = 0\)</span>
<ul>
<li>Expected values of error is zero. Model cannot be consistently high/low for certain subgroups of population</li>
</ul></li>
<li>Constant Variance Assumption: <span class="math inline">\(Var(E_i) = \sigma^2\)</span>
<ul>
<li>Model cannot be more accurate for certain groups, and more accurate for other groups.</li>
</ul></li>
<li>Independence Assumption: error terms 1 through <em>n</em> are independent random variables (later we assume <span class="math inline">\(E_i\)</span> ~ Normal)
<ul>
<li>Cannot be true that error terms can predict other error terms.</li>
</ul></li>
</ul>
<p>Model parameters <span class="math inline">\(\beta_{0}\)</span>, <span class="math inline">\(\beta_{1}\)</span>, and <span class="math inline">\(\sigma^2\)</span> are estimated based on data. You won’t know the true parameters.</p>
<p>To find these parameters, one approach is to find the values that minimize the sum of square errors.</p>
<div class="figure">
<img src="images/module1/estimation.png" alt="" />
<p class="caption">Model Estimation Approach</p>
</div>
<p>The above is derived from:</p>
<div class="figure">
<img src="images/module1/derivation.png" alt="" />
<p class="caption">Model Estimation Approach</p>
</div>
<p>Which results in the following fitted values and residuals:</p>
<div class="figure">
<img src="images/module1/fittedvalues.png" alt="" />
<p class="caption">Model Estimation Approach</p>
</div>
<p>The sample distrbution of the estimator of the variance <span class="math inline">\(\hat{\sigma^2}\)</span> is chi-squared with n-2 degrees of freedom, assuming normally distributed error terms.</p>
<p>I don’t really understand the next two slides very well, but including them here. It might be worth looking up what exactly a Chi-Squared distribution is, because I’m really not sure what she’s talking about here.</p>
<div class="figure">
<img src="images/module1/unk.png" alt="" />
<p class="caption">Variance Sampling Distribution 1</p>
</div>
<div class="figure">
<img src="images/module1/unk2.png" alt="" />
<p class="caption">Variance Sampling Distribution 2</p>
</div>
<p>Model Parameter Interpretation (behavior of <span class="math inline">\(\beta_1\)</span>:</p>
<ul>
<li>Positive Values: consistent with a direct relationship between x and y</li>
<li>Negative Values: consistent with an inverse relationship between x and y</li>
<li>Small (close to zero) Values: indicates there is not a significant relationship between x and y</li>
</ul>
<p><span class="math inline">\(\hat{\beta_1}\)</span> is the estimated expected change in the response variable associated with one unit of change in the predicting variable.</p>
<p><span class="math inline">\(\hat{\beta_0}\)</span> is the estimated expecteed value of response when the predicting variable equals zero.</p>
</div>
<div id="lesson-3---regression-concepts-estimation-example" class="section level3" number="1.1.3">
<h3><span class="header-section-number">1.1.3</span> Lesson 3 - Regression Concepts: Estimation Example</h3>
<p>This is the first example (predicting the effectiveness of a new advertising program on a medical company’s sales).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">&quot;Module 1/meddcor.txt&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>, <span class="at">header =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Response and predicting variable</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>sales <span class="ot">=</span> data[,<span class="dv">1</span>]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>adv <span class="ot">=</span> data[,<span class="dv">2</span>]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the linear regression model</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">lm</span>(sales <span class="sc">~</span> adv)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ adv)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -137.56  -92.63  -19.54   97.51  170.12 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -157.3301   145.1912  -1.084     0.29    
## adv            2.7721     0.2794   9.921 8.87e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 101.4 on 23 degrees of freedom
## Multiple R-squared:  0.8106, Adjusted R-squared:  0.8024 
## F-statistic: 98.43 on 1 and 23 DF,  p-value: 8.873e-10</code></pre>
<p>Above, see that <span class="math inline">\(\hat{\beta_0} = -157.3301\)</span>, <span class="math inline">\(\hat{\beta_1} = 2.7721\)</span>, and <span class="math inline">\(\hat\sigma = 101.4\)</span>.</p>
<p><strong>Questions:</strong></p>
<ol style="list-style-type: lower-alpha">
<li>What are the estimated regression coefficients and the estimated regression line?</li>
</ol>
<ul>
<li>Estimates are <span class="math inline">\(\hat{\beta_0} = -157.3301\)</span> and <span class="math inline">\(\hat{\beta_1} = 2.7721\)</span>.</li>
</ul>
<ol start="2" style="list-style-type: lower-alpha">
<li>Interpret the coefficients.</li>
</ol>
<ul>
<li>Sales increased by 2770 dollars with each 100 dollars in ad expense. Sales are in thousands and ad expense is in hundreds.</li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li>What does the model predict as the ad expense increases by 1000 dollars?</li>
</ol>
<ul>
<li>The increase in sales would be 27,700 dollars.</li>
</ul>
<ol start="4" style="list-style-type: lower-alpha">
<li>What would the sales be for an ad expense of 30 grand?</li>
</ol>
<ul>
<li>-157.33 + 300 x 2.77 = 673.67 thousands</li>
</ul>
<ol start="5" style="list-style-type: lower-alpha">
<li>What is the estimate of the error variance?</li>
</ol>
<ul>
<li>Estimate <span class="math inline">\(s^2\)</span> with MSE = 10,281.96 - This is from the square of the <em>residual standard error</em> in the R output.</li>
</ul>
<ol start="6" style="list-style-type: lower-alpha">
<li>What could you say about the sales for an ad expense of 100 grand?</li>
</ol>
<ul>
<li>Nothing, this is way outside of the range of observed values. We cannot predict sales because this would be extrapolation.</li>
</ul>
</div>
</div>
<div id="topic-1.2" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Topic 1.2</h2>
<div id="lesson-4---statistical-inference" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Lesson 4 - Statistical Inference</h3>
<div class="figure">
<img src="images/module1/estimator.png" alt="" />
<p class="caption">Derivation of the estimator</p>
</div>
<p>That the expectation of the estimator is exactly the true parameter is called <strong>unbiasedness</strong>. This is an important statistical property.</p>
<div class="figure">
<img src="images/module1/properties.png" alt="" />
<p class="caption">Properties</p>
</div>
<div class="figure">
<img src="images/module1/properties2.png" alt="" />
<p class="caption">Properties</p>
</div>
<p>All this leads to being able to compute the <strong>confidence intervals</strong> for <span class="math inline">\(\hat\beta_1\)</span> .</p>
<div class="figure">
<img src="images/module1/ci.png" alt="" />
<p class="caption">Confidence Interval for Beta 1</p>
</div>
<div class="figure">
<img src="images/module1/cideriv.png" alt="" />
<p class="caption">Confidence Interval Derivation for Beta 1</p>
</div>
<div class="figure">
<img src="images/module1/testing.png" alt="" />
<p class="caption">Hypothesis Testing for SS</p>
</div>
<p>But what if you want to test for different levels (i.e. not zero)?</p>
<div class="figure">
<img src="images/module1/testing2.png" alt="" />
<p class="caption">Testing at Different Levels</p>
</div>
<p>Or testing whether the regression coefficient is positive or negative? The p value will change, because we are only interested in one of the two tails..</p>
<div class="figure">
<img src="images/module1/testzero.png" alt="" />
<p class="caption">Testing Different from Zero</p>
</div>
<p>What about inference for the intercept parameter <span class="math inline">\(\hat\beta_0\)</span>?</p>
<div class="figure">
<img src="images/module1/intercept.png" alt="" />
<p class="caption">Inference for Intercept</p>
</div>
</div>
<div id="lesson-5---statistical-inference-examples" class="section level3" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> Lesson 5 - Statistical Inference Examples</h3>
<p>Back to the example of a medical company wanting to know whether it’s advertising spend is making a difference in sales.</p>
<p><em>What inferences can be made on the regression coefficients?</em></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ adv)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -137.56  -92.63  -19.54   97.51  170.12 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -157.3301   145.1912  -1.084     0.29    
## adv            2.7721     0.2794   9.921 8.87e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 101.4 on 23 degrees of freedom
## Multiple R-squared:  0.8106, Adjusted R-squared:  0.8024 
## F-statistic: 98.43 on 1 and 23 DF,  p-value: 8.873e-10</code></pre>
<ol style="list-style-type: lower-alpha">
<li>What is the estimate of the coefficient <span class="math inline">\(\beta_1\)</span> and its variance? What is its sampling distribution?</li>
</ol>
<ul>
<li>The estimate for <span class="math inline">\(\beta_1\)</span> is 2.7721. The variance estimate is <span class="math inline">\(0.2794^2\)</span>. The sampling distribution is a t-distribution with 23 (n-2) degrees of freedom.</li>
</ul>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the estimate of the coefficient <span class="math inline">\(\beta_0\)</span> and its variance?</li>
</ol>
<ul>
<li>The estimate for <span class="math inline">\(\beta_0\)</span> is -157.3301 and its variance is <span class="math inline">\(145.1912^2\)</span>.</li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li>Is the coefficient <span class="math inline">\(\beta_1\)</span> statistically significant? What is the p-value of the test? Interpret.</li>
</ol>
<ul>
<li>Yes - the estimate is statistically significant, the p-value is very very small 8.87 x 10^-10.</li>
</ul>
<p>d Is the coefficient <span class="math inline">\(\beta_1\)</span> statistically positive? What is the p-value of the test? Interpret.</p>
<p><span class="math inline">\(\beta_1\)</span> statistically positive: <span class="math inline">\(H_A: \beta_1 &gt; 0\)</span>. We accept the alternative hypothesis because the p-value is 4.43 X 10^-10.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>tvalue <span class="ot">=</span> <span class="fl">9.921</span> <span class="co"># comes from t-value of beta 1 in r output</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(tvalue, <span class="dv">23</span>))</span></code></pre></div>
<pre><code>## [1] 4.438411e-10</code></pre>
<ol start="5" style="list-style-type: lower-alpha">
<li>Obtain the 99% confidence interval for <span class="math inline">\(\beta_1\)</span></li>
</ol>
<p>The 99% confidence interval for <span class="math inline">\(\beta_1\)</span> is (1.988, 3.557)</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model, <span class="at">level=</span><span class="fl">0.99</span>)</span></code></pre></div>
<pre><code>##                   0.5 %    99.5 %
## (Intercept) -564.930546 250.27032
## adv            1.987712   3.55652</code></pre>
<ol start="6" style="list-style-type: lower-alpha">
<li>What is the p-value of a hypothesis testing procedure?</li>
</ol>
<p>The p-value is a measure of how rejectable the null hypothesis is. The smaller the p-value, the more rejectable the null hypothesis is for the observed data.</p>
</div>
<div id="lesson-6---regression-line-and-prediction" class="section level3" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Lesson 6 - Regression Line and Prediction</h3>
<p>Definitions of estimation vs. prediction below:</p>
<div class="figure">
<img src="images/module1/est.png" alt="" />
<p class="caption">Estimation vs. Prediction</p>
</div>
<p>The regression line is the same simple formula that’s always used (for simple linear regression).</p>
<div class="figure">
<img src="images/module1/line.png" alt="" />
<p class="caption">Estimating the Regression Line</p>
</div>
<p>If x* is away from the range of x’s, the variability of the estimation will be higher. The below slide shows this in the formula..</p>
<div class="figure">
<img src="images/module1/cimean.png" alt="" />
<p class="caption">Confidence Interval for Mean Response</p>
</div>
<ul>
<li>Predicting a new response contains two sources of uncertainty
<ul>
<li>Due to the new (n+1)th observation</li>
<li>Due to parameter estimates (betas)</li>
</ul></li>
</ul>
<div class="figure">
<img src="images/module1/response.png" alt="" />
<p class="caption">Predicting a New Response</p>
</div>
<div class="figure">
<img src="images/module1/response2.png" alt="" />
<p class="caption">Predicting a New Response 2</p>
</div>
<p>The <strong>prediction interval</strong> is not the same as the <strong>confidence interval</strong>, as the prediction interval is always wider than the confidence interval.</p>
</div>
<div id="lesson-7---regression-line-and-prediction-examples" class="section level3" number="1.2.4">
<h3><span class="header-section-number">1.2.4</span> Lesson 7 - Regression Line and Prediction Examples</h3>
<p>Same sales and advertising example.</p>
<p>What inferences can be made on the prediction of the sales given a targeted advertisement expenditure?</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ adv)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -137.56  -92.63  -19.54   97.51  170.12 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -157.3301   145.1912  -1.084     0.29    
## adv            2.7721     0.2794   9.921 8.87e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 101.4 on 23 degrees of freedom
## Multiple R-squared:  0.8106, Adjusted R-squared:  0.8024 
## F-statistic: 98.43 on 1 and 23 DF,  p-value: 8.873e-10</code></pre>
<ol style="list-style-type: lower-alpha">
<li>What sales would you predict for an advertisement expenditure of $30,000?</li>
</ol>
<p>This equals -157.33 + 300 x 2.77 = 673.67 thousand dollars.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the variance estimate of the estimated predicted sales for an advertisement expenditure of $30,000?</li>
</ol>
<div class="figure">
<img src="images/module1/formula.png" alt="" />
<p class="caption">Formula</p>
</div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">=</span> <span class="fu">mean</span>(adv)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(adv)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>mse <span class="ot">=</span> <span class="fl">101.4</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>var.beta1 <span class="ot">=</span> <span class="fl">0.2794</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Formula for Sxx</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>sxx <span class="ot">=</span> mse<span class="sc">/</span>var.beta1</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>pred.var <span class="ot">=</span> mse<span class="sc">*</span>(<span class="dv">1</span><span class="sc">+</span><span class="dv">1</span><span class="sc">/</span>n<span class="sc">+</span>(xbar<span class="dv">-300</span>)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>sxx)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>pred.var</span></code></pre></div>
<pre><code>## [1] 14286.16</code></pre>
<p>14,286.16 is the variance of the predicted sales.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>What are the lower and upper limits on predicted sales for an advertisement expenditure of $30,000 at 99% confidence level? How will the limits change if we lower the confidence level to 95%?</li>
</ol>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>new <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">adv =</span> <span class="dv">300</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;prediction interval 0.99&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;prediction interval 0.99&quot;</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict.lm</span>(model, new, <span class="at">interval =</span> <span class="st">&quot;predict&quot;</span>, <span class="at">level =</span> <span class="fl">0.99</span>)</span></code></pre></div>
<pre><code>##        fit     lwr      upr
## 1 674.3047 338.712 1009.897</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;prediction interval 0.95&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;prediction interval 0.95&quot;</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict.lm</span>(model, new, <span class="at">interval =</span> <span class="st">&quot;predict&quot;</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 674.3047 427.0146 921.5948</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;confidence interval 0.99&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;confidence interval 0.99&quot;</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict.lm</span>(model, new, <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>, <span class="at">level =</span> <span class="fl">0.99</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 674.3047 496.6497 851.9596</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;confidence interval 0.95&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;confidence interval 0.95&quot;</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict.lm</span>(model, new, <span class="at">interval =</span> <span class="st">&quot;confidence&quot;</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##        fit     lwr      upr
## 1 674.3047 543.395 805.2143</code></pre>
<p>The prediction intervals are simply the lower and upper bounds listed above.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Compare the confidence intervals of the estimated regression line versus the predicted regression line. Interpret.</li>
</ol>
<p>The prediction intervals are somewhat wider than the confidence intervals. The prediction intervals have additional variance from the variation of a new measurement.</p>
</div>
</div>
<div id="topic-1.3" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Topic 1.3</h2>
<div id="lesson-8---assumptions-and-diagnostics" class="section level3" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Lesson 8 - Assumptions and Diagnostics</h3>
<p>Same assumptions as discussed in a prior lesson (mean zero, constant variance, etc.).</p>
<p><strong>Residual Analysis</strong></p>
<p>Plot the residuals <span class="math inline">\(e_i\)</span></p>
<p>If the scatter plot of <span class="math inline">\(e_i\)</span> is not random around a zero line:</p>
<ul>
<li>the relationship between X and Y is not linear</li>
<li>variances of error terms are not equal</li>
<li>response data are not independent</li>
</ul>
<p>If the graph looks like and upside down u, then the relationship is not linear. Or, if it shows a “megaphone” pattern, it’s not linear. Also, clusters of residuals may tell you that the independence assumption does not hold.</p>
<ul>
<li>However, independence is a complicated assumption to validate. Residual analysis is just checking for uncorrelated errors (<em>not</em> independence)</li>
</ul>
<p>The assumption of normality can be checked using a <strong>normal probability plot</strong>. <em>Don’t do this by hand, let R do it for you</em>.</p>
<div class="figure">
<img src="images/module1/normality.png" alt="" />
<p class="caption">Checking for Normality</p>
</div>
<p>You can also just check a histogram of the residuals, and see if it looks like a standard bell curve. If it doesn’t, then the normality assumption may not hold.</p>
<p><strong>Variable Transformation</strong></p>
<ul>
<li>The relationship between X and Y may not be exactly linear.</li>
<li>You can transform X by some nonlinear function such as <span class="math inline">\(f(x) = x^a\)</span> or <span class="math inline">\(f(x) = log(x)\)</span> to model the nonlinear relationship.</li>
</ul>
<p>What if the normality or constant variance assumption does not hold? Use a transformation that stabilizes the response variable.</p>
<div class="figure">
<img src="images/module1/transform.png" alt="" />
<p class="caption">Normality Transformations</p>
</div>
<p>If that doesn’t fix it, you may need to try a different modeling approach.</p>
</div>
<div id="lesson-9---outliers-and-model-performance" class="section level3" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Lesson 9 - Outliers and Model Performance</h3>
<div class="figure">
<img src="images/module1/outliers.png" alt="" />
<p class="caption">Outlier Definitions</p>
</div>
<p>Sometimes the outliers just belong to the data, and removing that point can skew or bias your analysis. Sometimes you just have to perform the analysis with and without the outlier and inform the reader about the differences between models.</p>
<div class="figure">
<img src="images/module1/outliers2.png" alt="" />
<p class="caption">Checking for Outliers</p>
</div>
<p>Is the model a good fit?</p>
<p><img src="images/module1/r2.png" alt="Coefficient of Determination" />
R2 is the proportion of total variability in Y that can be explained by the regression.</p>
<p>Another approach is the <strong>Correlation Coefficient</strong></p>
<div class="figure">
<img src="images/module1/cc.png" alt="" />
<p class="caption">Correlation Coefficient</p>
</div>
</div>
<div id="lesson-10---model-diagnostic-example" class="section level3" number="1.3.3">
<h3><span class="header-section-number">1.3.3</span> Lesson 10 - Model Diagnostic Example</h3>
<p>Same example as before.</p>
<p><em>Do the assumptions of the linear regression model hold? What is the explanatory power of the model?</em></p>
<ol style="list-style-type: lower-alpha">
<li>What are the assumptions of linear regression?</li>
</ol>
<ul>
<li>Linearity</li>
<li>Constant Variance</li>
<li>Independence</li>
<li>Normality</li>
</ul>
<ol start="2" style="list-style-type: lower-alpha">
<li>Do the assumptions hold? Provide the graphical displays needed to support the diagnostics. Interpret.</li>
</ol>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># simple scatter plot against variables</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(adv, sales)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Yep, the above looks linear..</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fitted values vs. residuals</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model<span class="sc">$</span>fitted, model<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The above validates the constant variance assumption (and uncorrelated errors). The residuals are scattered about the zero line.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car); <span class="fu">qqPlot</span>(model<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre><code>## [1] 19  5</code></pre>
<p>The above validates the independence assumption. However, there does appear to be a heavy right tail.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Do you identify any outliers?</li>
</ol>
<p>There do not appear to be any outliers in the data based on the above plots.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>How much variability in sales is explained by the advertising expenditure?</li>
</ol>
<p>Around 81.0591863% of the variability in sales is explained by the advertising expenditure.</p>
</div>
</div>
<div id="topic-1.4" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Topic 1.4</h2>
<div id="lesson-11---testing-the-theory-of-purchasing-power-parity-part-1" class="section level3" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> Lesson 11 - Testing the Theory of Purchasing Power Parity (Part 1)</h3>
<p>PPP = Over long periods of time, exchange rate changes tend to offset inflation rate changes across different countries. (I think?)</p>
<div class="figure">
<img src="images/module1/inflate.png" alt="" />
<p class="caption">PPP Set Up</p>
</div>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use read.table command (pay attention to file type)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ppp <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">&quot;Module 1/ppp.dat&quot;</span>, <span class="at">sep=</span><span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>, <span class="at">header=</span>T, <span class="at">row.names =</span> <span class="cn">NULL</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># how many countries?</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ppp)</span></code></pre></div>
<pre><code>## [1] 40  4</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Brazil is an outlier and was not included initially - add Brazil back in</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>Addp <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="st">&quot;Brazil&quot;</span>,<span class="sc">-</span><span class="dv">76</span>,<span class="sc">-</span><span class="dv">73</span>,<span class="dv">0</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Addp) <span class="ot">=</span> <span class="fu">names</span>(ppp)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># attach to original dataframe</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>ppp <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="fu">rbind</span>(ppp,Addp))</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(ppp)</span></code></pre></div>
<p><strong>Exploratory Data Analysis</strong></p>
<ul>
<li>Evaluate the linear relationship - scatter plot of two variables</li>
</ul>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Inflation.difference, Exchange.rate.change, <span class="at">main =</span> <span class="st">&quot;Scatterplot of Exchange Rate Change vs. Inflation Difference&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Inflation Difference&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Exchange Rate Change&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-12-1.png" width="672" />
<em>Evaluate differences between developed and developing countries</em></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Exchange.rate.change<span class="sc">~</span><span class="fu">as.factor</span>(Developed), <span class="at">main =</span> <span class="st">&quot;Boxplot of Exchange Rate Change by Developed vs. Developing Countries&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Country Class&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Exchange Rate Change&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>From the above, you can see there is a linear relationship and a significant difference between developing and developed countries in exchange rate changes.</p>
<p>Now, create a linear regression model.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>pppa <span class="ot">=</span> <span class="fu">lm</span>(Exchange.rate.change <span class="sc">~</span> Inflation.difference)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pppa)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Exchange.rate.change ~ Inflation.difference)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.5992 -0.7169  0.1732  0.8852  2.8100 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          -1.51930    0.29415  -5.165 7.43e-06 ***
## Inflation.difference  0.96185    0.01781  53.991  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.646 on 39 degrees of freedom
## Multiple R-squared:  0.9868, Adjusted R-squared:  0.9865 
## F-statistic:  2915 on 1 and 39 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>PPP theory would say that the intercept would be zero and the slope would be 1, however that’s not what is observed above. Testing the intercept (since the value should be zero) is as easy as looking at the p-value, however checking whether <span class="math inline">\(\beta_1\)</span> is different from 1 is different, see slide below.</p>
<div class="figure">
<img src="images/module1/theory.png" alt="" />
<p class="caption">Testing the Theory</p>
</div>
<p>The p value is small, but not very small. (Prefer 0.01). Violations of PPP with respect to the intercept, and possibly with the slope.</p>
<p>Now, time for some hypothesis testing in R.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(pppa,<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">rhs=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## Inflation.difference = 1
## 
## Model 1: restricted model
## Model 2: Exchange.rate.change ~ Inflation.difference
## 
##   Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
## 1     40 118.14                              
## 2     39 105.70  1    12.432 4.5869 0.03852 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Or, you can compute the tvalue and pvalue as follows</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>tvalue <span class="ot">=</span> <span class="sc">-</span>(<span class="fl">0.9618</span><span class="dv">-1</span>)<span class="sc">/</span><span class="fl">0.01781</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>pvalue <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pt</span>(tvalue,<span class="dv">39</span>))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pvalue)</span></code></pre></div>
<pre><code>## [1] 0.03825067</code></pre>
</div>
<div id="lesson-12---testing-the-theory-of-purchasing-power-parity-part-2" class="section level3" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> Lesson 12 - Testing the Theory of Purchasing Power Parity (Part 2)</h3>
<p><strong>Confidence Bands in R</strong></p>
<p>The fitted line plot shows several lines:</p>
<ul>
<li>The continuous line is the fitted regression line</li>
<li>The wider interrupted line band is the prediction confidence band</li>
<li>The narrower interrupted line band is the confidence band</li>
<li>The circles correspond to outliers</li>
</ul>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function for fitted line plot (copied from example code)</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>regplot.confbands.fun <span class="ot">&lt;-</span> <span class="cf">function</span>(x,y,<span class="at">confidencelevel=</span>.<span class="dv">95</span>,<span class="at">CImean=</span>T,<span class="at">PI=</span>T,<span class="at">CIregline=</span>F,<span class="at">legend=</span>F){</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="do">#### Modified from a function written by Sandra McBride, Duke University</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="do">#### For a simple linear regression line, this function</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="do">#### will plot the line, CI for mean response, prediction intervals, </span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="do">#### and (optionally) a simulataneous CI for the regression line.</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>    xx <span class="ot">&lt;-</span> x[<span class="fu">order</span>(x)]</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>    yy <span class="ot">&lt;-</span> y[<span class="fu">order</span>(x)]</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>    lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(yy<span class="sc">~</span>xx)    </span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(xx,yy,<span class="at">ylim=</span><span class="fu">c</span>(<span class="fu">min</span>(yy),(<span class="fu">max</span>(yy)<span class="sc">+</span>.<span class="dv">2</span><span class="sc">*</span><span class="fu">max</span>(yy))),<span class="at">main=</span><span class="st">&quot;Fitted Line Plot&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Exchange rate change&quot;</span>,</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">xlab=</span><span class="st">&quot;Inflation difference&quot;</span>)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abline</span>(lm1<span class="sc">$</span>coefficients)</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>    <span class="do">#### calculation of components of intervals ####</span></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>    n <span class="ot">&lt;-</span> <span class="fu">length</span>(yy)</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>    sx2 <span class="ot">&lt;-</span> (<span class="fu">var</span>(xx))</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>    shat <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm1)<span class="sc">$</span>sigma</span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>    s2hat <span class="ot">&lt;-</span> shat<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>    SEmuhat <span class="ot">&lt;-</span> shat<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>n<span class="sc">+</span> ((xx<span class="sc">-</span><span class="fu">mean</span>(xx))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>((n<span class="dv">-1</span>)<span class="sc">*</span>sx2))</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a>    SEpred <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(s2hat<span class="sc">+</span>SEmuhat<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb45-21"><a href="#cb45-21" aria-hidden="true" tabindex="-1"></a>    t.quantile <span class="ot">&lt;-</span> <span class="fu">qt</span>(confidencelevel,lm1<span class="sc">$</span>df.residual)</span>
<span id="cb45-22"><a href="#cb45-22" aria-hidden="true" tabindex="-1"></a>    <span class="do">####</span></span>
<span id="cb45-23"><a href="#cb45-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (CImean<span class="sc">==</span>T){</span>
<span id="cb45-24"><a href="#cb45-24" aria-hidden="true" tabindex="-1"></a>        mean.up <span class="ot">&lt;-</span> lm1<span class="sc">$</span>fitted<span class="sc">+</span>t.quantile<span class="sc">*</span>SEmuhat</span>
<span id="cb45-25"><a href="#cb45-25" aria-hidden="true" tabindex="-1"></a>        mean.down <span class="ot">&lt;-</span> lm1<span class="sc">$</span>fitted<span class="sc">-</span>t.quantile<span class="sc">*</span>SEmuhat</span>
<span id="cb45-26"><a href="#cb45-26" aria-hidden="true" tabindex="-1"></a>        <span class="fu">lines</span>(xx,mean.up,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb45-27"><a href="#cb45-27" aria-hidden="true" tabindex="-1"></a>        <span class="fu">lines</span>(xx,mean.down,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb45-28"><a href="#cb45-28" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb45-29"><a href="#cb45-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (PI<span class="sc">==</span>T){</span>
<span id="cb45-30"><a href="#cb45-30" aria-hidden="true" tabindex="-1"></a>        PI.up <span class="ot">&lt;-</span> lm1<span class="sc">$</span>fitted<span class="sc">+</span>t.quantile<span class="sc">*</span>SEpred</span>
<span id="cb45-31"><a href="#cb45-31" aria-hidden="true" tabindex="-1"></a>        PI.down <span class="ot">&lt;-</span> lm1<span class="sc">$</span>fitted<span class="sc">-</span>t.quantile<span class="sc">*</span>SEpred</span>
<span id="cb45-32"><a href="#cb45-32" aria-hidden="true" tabindex="-1"></a>        <span class="fu">lines</span>(xx,PI.up,<span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb45-33"><a href="#cb45-33" aria-hidden="true" tabindex="-1"></a>        <span class="fu">lines</span>(xx,PI.down,<span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb45-34"><a href="#cb45-34" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb45-35"><a href="#cb45-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (CIregline<span class="sc">==</span>T){</span>
<span id="cb45-36"><a href="#cb45-36" aria-hidden="true" tabindex="-1"></a>        HW <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">2</span><span class="sc">*</span><span class="fu">qf</span>(confidencelevel,n<span class="sc">-</span>lm1<span class="sc">$</span>df.residual,lm1<span class="sc">$</span>df.residual))<span class="sc">*</span>SEmuhat </span>
<span id="cb45-37"><a href="#cb45-37" aria-hidden="true" tabindex="-1"></a>        CIreg.up <span class="ot">&lt;-</span> lm1<span class="sc">$</span>fitted<span class="sc">+</span>HW</span>
<span id="cb45-38"><a href="#cb45-38" aria-hidden="true" tabindex="-1"></a>        CIreg.down <span class="ot">&lt;-</span> lm1<span class="sc">$</span>fitted<span class="sc">-</span>HW</span>
<span id="cb45-39"><a href="#cb45-39" aria-hidden="true" tabindex="-1"></a>        <span class="fu">lines</span>(xx,CIreg.up,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb45-40"><a href="#cb45-40" aria-hidden="true" tabindex="-1"></a>        <span class="fu">lines</span>(xx,CIreg.down,<span class="at">lty=</span><span class="dv">4</span>)</span>
<span id="cb45-41"><a href="#cb45-41" aria-hidden="true" tabindex="-1"></a>    }   </span>
<span id="cb45-42"><a href="#cb45-42" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (legend<span class="sc">==</span>T){</span>
<span id="cb45-43"><a href="#cb45-43" aria-hidden="true" tabindex="-1"></a>        choices <span class="ot">&lt;-</span> <span class="fu">c</span>(CImean,PI,CIregline)</span>
<span id="cb45-44"><a href="#cb45-44" aria-hidden="true" tabindex="-1"></a>        line.type <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>)</span>
<span id="cb45-45"><a href="#cb45-45" aria-hidden="true" tabindex="-1"></a>             names.line <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;CI for mean resp.&quot;</span>,<span class="st">&quot;Prediction Int.&quot;</span>,<span class="st">&quot;CI for reg. line&quot;</span>)</span>
<span id="cb45-46"><a href="#cb45-46" aria-hidden="true" tabindex="-1"></a>        <span class="fu">legend</span>(<span class="fu">max</span>(xx)<span class="sc">-</span>.<span class="dv">2</span><span class="sc">*</span><span class="fu">max</span>(xx),<span class="fu">max</span>(yy)<span class="sc">+</span>.<span class="dv">2</span><span class="sc">*</span><span class="fu">max</span>(yy),<span class="at">legend=</span>names.line[choices],<span class="at">lty=</span>line.type[choices])</span>
<span id="cb45-47"><a href="#cb45-47" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb45-48"><a href="#cb45-48" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb45-49"><a href="#cb45-49" aria-hidden="true" tabindex="-1"></a><span class="fu">regplot.confbands.fun</span>(ppp<span class="sc">$</span>Inflation.difference,ppp<span class="sc">$</span>Exchange.rate.change)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p><strong>Confidence and Prediction Intervals</strong></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new data point</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>newppp <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">Inflation.difference =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.68</span>))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># specify whether you want a confidence or prediction interval</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(pppa, newppp, <span class="at">interval=</span><span class="fu">c</span>(<span class="st">&quot;confidence&quot;</span>))</span></code></pre></div>
<pre><code>##         fit       lwr       upr
## 1 -2.173351 -2.756818 -1.589884</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(pppa, newppp, <span class="at">interval=</span><span class="fu">c</span>(<span class="st">&quot;prediction&quot;</span>))</span></code></pre></div>
<pre><code>##         fit       lwr      upr
## 1 -2.173351 -5.554071 1.207369</code></pre>
<p><strong>Residual Analysis in R</strong></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ppp<span class="sc">$</span>Inflation.difference, <span class="fu">residuals</span>(pppa),<span class="at">xlab=</span><span class="st">&quot;Inflation Difference&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Residuals&quot;</span>,<span class="at">main=</span><span class="st">&quot;Versus Predictor&quot;</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(pppa),<span class="fu">residuals</span>(pppa),<span class="at">xlab=</span><span class="st">&quot;Fitted values&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Residuals&quot;</span>,<span class="at">main=</span><span class="st">&quot;Versus Fits&quot;</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(pppa))</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">lty=</span><span class="dv">1</span>,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">residuals</span>(pppa),<span class="at">main=</span><span class="st">&quot;Histogram of residuals&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>First plot</p>
<ul>
<li>Used to evaluate linearity assumption. No pattern = linearity assumption holds. This one looks good. However, can identify outlier in this plot.</li>
</ul>
<p>Second Plot</p>
<ul>
<li>Used to evaluate constant variance and uncorrelated errors assumption. Constant variance doesn’t seem to hold here. No groupings of points, indicating assumption of uncorrelated errors probably holds.</li>
</ul>
<p>Third Plot and Forth Plot</p>
<ul>
<li>Can tell from both of these that the distribution is slightly skewed.</li>
</ul>
<p>The data point for Brazil is a <strong>leverage point</strong>. It had a period of hyperinflation from 1980 to 1994. This point has the potential to change the results of the regression, so it’s a good idea to remove and explain the difference between models.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="do">##### Repeat Analysis: Omit Brazil #########</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>newppp <span class="ot">=</span> ppp[ppp<span class="sc">$</span>Country<span class="sc">!=</span><span class="st">&quot;Brazil&quot;</span>,]</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co">#attach(newppp)</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(newppp<span class="sc">$</span>Inflation.difference,newppp<span class="sc">$</span>Exchange.rate.change, <span class="at">main=</span><span class="st">&quot;Scatterplot of Exchange rate change </span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="st">     vs Inflation difference&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Inflation difference&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Exchange rate change&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>pppn <span class="ot">=</span> <span class="fu">lm</span>(newppp<span class="sc">$</span>Exchange.rate.change <span class="sc">~</span> newppp<span class="sc">$</span>Inflation.difference)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pppn)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = newppp$Exchange.rate.change ~ newppp$Inflation.difference)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.5698 -0.3839  0.2119  0.7634  2.6864 
## 
## Coefficients:
##                             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                 -1.37222    0.30517  -4.497 6.31e-05 ***
## newppp$Inflation.difference  0.99152    0.02626  37.757  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.62 on 38 degrees of freedom
## Multiple R-squared:  0.974,  Adjusted R-squared:  0.9734 
## F-statistic:  1426 on 1 and 38 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(pppn,<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">rhs=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## newppp$Inflation.difference = 1
## 
## Model 1: restricted model
## Model 2: newppp$Exchange.rate.change ~ newppp$Inflation.difference
## 
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1     39 99.941                           
## 2     38 99.667  1   0.27372 0.1044 0.7484</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4 in 1 residual plot. </span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(newppp<span class="sc">$</span>Inflation.difference, <span class="fu">residuals</span>(pppn),<span class="at">xlab=</span><span class="st">&quot;Inflation Difference&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Residuals&quot;</span>,<span class="at">main=</span><span class="st">&quot;Versus Predictor&quot;</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(pppn),<span class="fu">residuals</span>(pppn),<span class="at">xlab=</span><span class="st">&quot;Fitted values&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Residuals&quot;</span>,<span class="at">main=</span><span class="st">&quot;Versus Fits&quot;</span>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(pppn))</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">lty=</span><span class="dv">1</span>,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">residuals</span>(pppn),<span class="at">main=</span><span class="st">&quot;Histogram of residuals&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Residuals&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-20-2.png" width="672" /></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div>
<p>With the above model, we see violations of PPP with respect to the intercept only (cannot reject null hypothesis of slope B1).</p>
<p>Also, there is now another outlier (Indonesia). Do you just keep taking the points out or leave them in? Or does this just say something about developing countries?</p>
<ul>
<li>For developed countries, the changes in inflation difference seem to be balance by exchange rate changes</li>
<li>For developing countries, the case for PPP is considerably weaker.</li>
<li>Conclusion: PPP is not robust to unusual economic or political conditions.</li>
</ul>
</div>
<div id="lesson-13---2000-presidential-election-in-florida" class="section level3" number="1.4.3">
<h3><span class="header-section-number">1.4.3</span> Lesson 13 - 2000 Presidential Election in Florida</h3>
<p>Bush v. Gore was very close, Florida was a key state. Palm Beach county had a large count of votes for another republican candidate (Buchanan). Were the Buchanan votes in Palm Beach County really meant for Bush?</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>elections <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">&quot;Module 1/elections.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>elections[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,]</span></code></pre></div>
<pre><code>##   co  lat  lon   npop whit blac hisp  o65 hsed coll  inco  bush  gore brow nade
## 1  1 29.7 82.4 198326 74.4 21.8  4.7  9.4 82.7 34.6 19412 34124 47365  658 3226
## 2  2 30.3 82.3  20761 82.4 16.8  1.5  7.7 64.1  5.7 14859  5610  2392   17   53
## 3  3 30.2 85.6 146223 84.2 12.4  2.4 11.9 74.7 15.7 17838 38637 18850  171  828
## 4  4 29.9 82.2  24646 76.1 22.9  2.6 11.8 65.0  8.1 13681  5414  3075   28   84
##   harr hage buch mcre phil moor
## 1    6   42  263    4   20   21
## 2    0    3   73    0    3    3
## 3    5   18  248    3   18   27
## 4    0    2   65    0    2    3</code></pre>
<p>A lot of factors - really only interested in the votes for Bush and Buch..</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Extract number of votes for each candidate</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>buch <span class="ot">=</span> elections<span class="sc">$</span>buch</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>bush <span class="ot">=</span> elections<span class="sc">$</span>bush</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bush,buch,<span class="at">ylab=</span><span class="st">&quot;Number of votes for Buchanan&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Number of votes for Bush&quot;</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;Number of votes by county in Florida&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(buch,bush)</span></code></pre></div>
<pre><code>## [1] 0.6250012</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># I would say that the line appears to be curvilinear and therefore</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># simple linear regressions would not capture the non-linearities.</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co"># However there does appear to be a linear relationship, positive, that</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="co"># is supported by the correlation and visual inspection of the</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># scatter plot.</span></span></code></pre></div>
<p>Note that the scatter plot indicates both 1) a strong positive relationship between the number of votes for the two candidates (except outliers) and 2) curvature in the relationship - need to consider transformations. Note correlation coef above.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(bush),<span class="fu">log</span>(buch),<span class="at">ylab=</span><span class="st">&quot;Log of Number of votes for Buchanan&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Log of Number of votes for Bush&quot;</span>,</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="at">main=</span><span class="st">&quot;Number of votes by county in Florida&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">log</span>(buch),<span class="fu">log</span>(bush))</span></code></pre></div>
<pre><code>## [1] 0.9221706</code></pre>
<p>Correlation coef is a lot better after the log transforms of both variables, data is much more linear and this should be used.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">=</span> <span class="fu">lm</span>(<span class="fu">log</span>(buch) <span class="sc">~</span> <span class="fu">log</span>(bush))</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(buch) ~ log(bush))
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.97038 -0.24247  0.00825  0.25452  1.65752 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2.55079    0.38903  -6.557 1.04e-08 ***
## log(bush)    0.75620    0.03934  19.222  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4672 on 65 degrees of freedom
## Multiple R-squared:  0.8504, Adjusted R-squared:  0.8481 
## F-statistic: 369.5 on 1 and 65 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model)</span></code></pre></div>
<pre><code>##                  2.5 %     97.5 %
## (Intercept) -3.3277351 -1.7738363
## log(bush)    0.6776289  0.8347638</code></pre>
<p><em>Interpretation</em></p>
<ul>
<li><p>As number of log-votes for bush increase by 1% the expected % increase of log-votes for buch is 0.756, and the standard error is .03934.</p></li>
<li><p>The min % increase is 0.677 and the max % increase is 0.834.</p></li>
</ul>
<p><img src="images/module1/analysis.png" alt="Analysis" />
<strong>Residual Analysis</strong></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Residual Analysis</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">log</span>(bush),<span class="fu">resid</span>(model), <span class="at">main=</span><span class="st">&quot;Predictors vs Residuals&quot;</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(model),<span class="fu">resid</span>(model),<span class="at">main=</span><span class="st">&quot;Fitted vs Residuals&quot;</span>,</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">&quot;Fitted Values&quot;</span>)</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">0</span>)</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(model),<span class="at">main=</span><span class="st">&quot;QQ-Plot of Residuals&quot;</span>)</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">resid</span>(model))</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(model),<span class="at">main=</span><span class="st">&quot;Histogram of Residuals&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<ul>
<li>Validity of linear assumption, by plot 1, validated.</li>
<li>Looks like maybe one outlier, 2,3,4.</li>
<li>Normality of Errors plot 3,4 looks like there is a negative outlier by QQ and hist</li>
<li>Heteroskedasticity. Plot 2. Appears fairly constant, excepting a couple negative outliers</li>
</ul>
<p>Is Palm Beach an Outlier?</p>
<ul>
<li>We need to remove Palm Beach from the regression analysis.</li>
</ul>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Omit Palm Beach</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>model.red <span class="ot">=</span> <span class="fu">lm</span>(<span class="fu">log</span>(buch[<span class="sc">-</span><span class="dv">50</span>])<span class="sc">~</span><span class="fu">log</span>(bush[<span class="sc">-</span><span class="dv">50</span>]))</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.red)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(buch[-50]) ~ log(bush[-50]))
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.97136 -0.22384  0.02279  0.26959  1.00652 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    -2.31657    0.35470  -6.531 1.23e-08 ***
## log(bush[-50])  0.72960    0.03599  20.271  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4203 on 64 degrees of freedom
## Multiple R-squared:  0.8652, Adjusted R-squared:  0.8631 
## F-statistic: 410.9 on 1 and 64 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now, we predict the vote counts for Palm beach given the new fitted model.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Obtain the predicted vote count for Palm Beach given the fitted model without</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>new <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">bush =</span> bush[<span class="dv">50</span>])</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="do">## The difference between predicted on the original scale and the observed vote count </span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>buch[<span class="dv">50</span>]<span class="sc">-</span><span class="fu">exp</span>(<span class="fu">predict</span>(model.red,new))</span></code></pre></div>
<pre><code>##        1 
## 2809.498</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Prediction Confidence Interval for log(vote count) </span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model.red,new,<span class="at">interval=</span><span class="st">&#39;prediction&#39;</span>,<span class="at">level=</span>.<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 6.392757 5.532353 7.253162</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Prediction Confidence Interval on the original scale </span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">predict</span>(model.red,new,<span class="at">interval=</span><span class="st">&#39;prediction&#39;</span>,<span class="at">level=</span>.<span class="dv">95</span>))</span></code></pre></div>
<pre><code>##        fit     lwr      upr
## 1 597.5019 252.738 1412.564</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>buch[<span class="dv">50</span>]</span></code></pre></div>
<pre><code>## [1] 3407</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Therefore, what we can say is that it is likely that Palm Beach is a different community</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="co"># That comes from a different model than the rest of the </span></span></code></pre></div>
<p>The second confidence interval above is in the original scale. We see that the actual number of votes for buchanan (3407) was a lot greater than the upper bound of the prediction interval, suggesting that this is an outlier. The court decision was that George Bush won the 2000 election by 537 votes, suggesting that he may have actually won by a wider margin? Not sure about the interpretation here to be honest.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
